name: ebisu_py
version: 0.0.1
author: Daniel Davidson <dbdavidson@yahoo.com>
homepage: https://github.com/patefacio/ebisu_py
dependencies:

# custom <ebisu_py dependencies>
# end <ebisu_py dependencies>

dev_dependencies:
  yaml: "any"
  browser: "any"
  hop: "any"
  hop_docgen: "any"

# custom <ebisu_py dev dependencies>
# end <ebisu_py dev dependencies>

dependency_overrides:
# custom <ebisu_py dependency overrides>
# end <ebisu_py dependency overrides>

transformers:

# custom <ebisu_py transformers>
# end <ebisu_py transformers>

