name: ebisu_py
version: 0.0.1
homepage: https://github.com/patefacio/ebisu_py
environment:
  sdk: '>=1.8.2 <2.0.0'

dependencies:

# custom <ebisu_py dependencies>
# end <ebisu_py dependencies>

dev_dependencies:

# custom <ebisu_py dev dependencies>

  ebisu: "^0.6.18"
  test: "^0.12.0"

# end <ebisu_py dev dependencies>

dependency_overrides:
# custom <ebisu_py dependency overrides>
# end <ebisu_py dependency overrides>

transformers:

# custom <ebisu_py transformers>
# end <ebisu_py transformers>

